Items = {
  bread = {
    label       = "Bread",
    description = "Staves off hunger.",
    weight      = 0.5,
    stack       = true,
    degrade     = 0,
    decay       = false,
    close       = true,
    consume     = 1,
    allowArmed  = false,
    -- server-side hook: either an event name or export "resource:Function"
    server      = { event = "bread:serverUse", export = nil },
    -- client-side hook (will be triggered on player client)
    client      = { event = "bread:clientUse", export = nil },
    event       = "bread:eaten", -- legacy field (kept for compatibility)
    status      = { hunger = 200000 },
    anim        = { dict="mp_player_inteat@burger", clip="mp_player_int_eat_burger" },
    prop        = {
      model = "prop_cs_burger_01",
      pos   = { x=0.005, y=0.005, z=-0.005 },
      rot   = { x=-50.0, y=0.0, z=0.0 },
      bone  = 18905,
    },
    disable     = { move=true, combat=true, sprint=true },
    usetime     = 5000,
    cancel      = true,
    buttons     = {
      { label="Share",   action=function(slot) print("Share slot",slot) end },
      { label="Inspect", action=function(slot) print("Inspect slot",slot) end },
    },
    category    = "food",        -- ← here
    imageUrl    = "https://cdn.imgbin.com/6/12/8/imgbin-bread-y1UUXsEqPpfLzpMbNRMEePuj0.jpg",
  },

  water = {
    label       = "Water Bottle",
    weight      = 0.8,
    stack       = true,
    close       = false,
    consume     = 1,
    server      = { event = nil, export = nil },
    client      = { event = nil, export = nil },
    buttons     = {
      { label="Drink", action=function(slot) print("Drank from slot",slot) end },
    },
    category    = "food",
    imageUrl    = "https://via.placeholder.com/64?text=💧",
  },

  pickaxe = {
    label       = "Pickaxe",
    weight      = 4.0,
    stack       = false,
    consume     = 0.1,
    degrade     = 30,
    decay       = true,
    close       = true,
    server      = { event = nil, export = nil },
    client      = { event = "resource:mineNode", export = nil },
    buttons     = {
      { label="Sharpen", action=function(slot) print("Sharpen slot",slot) end },
    },
    category    = "tools",
    image       = "pickaxe.png",  -- will load from `img/pickaxe.png`
  },

  -- Example additional items
  bandage = {
    label       = "Bandage",
    description = "Stops minor bleeding and heals a small amount.",
    weight      = 0.1,
    stack       = true,
    consume     = 1,
    usetime     = 1500,
    close       = true,
    server      = { event = "bandage:serverUse", export = nil },
    client      = { event = "bandage:clientUse", export = nil },
    status      = { bleed = -1, health = 20000 },
    anim        = { dict="missheistdockssetup1clipboard@base", clip="base" },
    category    = "medical",
    imageUrl    = "https://via.placeholder.com/64?text=🩹",
  },

medkit = {
  label       = "Medkit",
  description = "Heals a large amount of health and removes status effects.",
  weight      = 1.5,
  stack       = false,
  consume     = 1,
  usetime     = 5000,
  close       = true,
  server      = { event = "medkit:serverUse", export = nil },
  client      = { event = "medkit:clientUse", export = nil },
  status      = { health = 150000, bleed = -1, pain = -1 },
  -- animation: explicit duration = usetime (ms), non-looping flag
  anim        = {
    dict        = "amb@medic@standing@tendtodead@base",
    clip        = "base",
    duration    = 5000,    -- <-- match usetime (ms)
    flag        = 0,       -- non-looping safe default; you can change if you need looping
    blendIn     = 8.0,
    blendOut    = -8.0,
    playbackRate = 1.0,
  },
  -- prop attached to hand (tweak pos/rot as needed)
  prop        = {
    model = "prop_ld_case_01",
    pos = { x = 0.08, y = 0.02, z = -0.02 },
    rot = { x = 0.0, y = 0.0, z = 0.0 },
    bone = 18905
  },
  disable     = { move = true, combat = true, sprint = true },
  category    = "medical",
  imageUrl    = "https://via.placeholder.com/64?text=+",
},


  lockpick = {
    label = "Lockpick",
    description = "Used to break into cars/doors via a lockpicking minigame.",
    weight = 0.05,
    stack = true,
    consume = 0.25,
    degrade = 10,
    close = true,
    usetime = 1500,
    server = { event = "lockpicking:attempt", export = nil },
    client = { event = "lockpicking:clientOpenMinigame", export = nil },
    category = "tools",
    image = "lockpick.png",
  },

  gas_can = {
    label = "Gas Can",
    description = "Refuels a vehicle when used near one.",
    weight = 8.0,
    stack = false,
    consume = 1,
    close = true,
    usetime = 4000,
    server = { event = "vehicle:serverRefuel", export = nil },
    client = { event = "vehicle:refuel", export = nil },
    category = "vehicle",
    imageUrl = "https://via.placeholder.com/64?text=⛽",
  },

  repair_kit = {
    label = "Repair Kit",
    description = "Repairs vehicle health when used next to a vehicle.",
    weight = 3.0,
    stack = false,
    consume = 1,
    usetime = 5000,
    server = { event = "vehicle:serverRepair", export = nil },
    client = { event = "vehicle:repair", export = nil },
    category = "vehicle",
    imageUrl = "https://via.placeholder.com/64?text=🔧",
  },

  weapon_pistol = {
    label       = "Pistol",
    description = "A standard 9mm sidearm.",
    weight      = 3.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_PISTOL",  -- the native weapon hash name
    ammo        = 50,               -- optional starting ammo
    image       = "pistol.png",
  },

  weapon_pistol_mk2 = {
    label       = "Pistol MK2",
    description = "Upgraded pistol.",
    weight      = 3.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_PISTOL_MK2",
    ammo        = 60,
    image       = "pistol_mk2.png",
  },

  weapon_combatpistol = {
    label       = "Combat Pistol",
    description = "Faster-firing pistol.",
    weight      = 3.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_COMBATPISTOL",
    ammo        = 60,
    image       = "combat_pistol.png",
  },

  weapon_appistol = {
    label       = "AP Pistol",
    description = "Armor-piercing pistol.",
    weight      = 3.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_APPISTOL",
    ammo        = 60,
    image       = "ap_pistol.png",
  },

  weapon_pistol50 = {
    label       = "Pistol .50",
    description = "Heavy .50 pistol.",
    weight      = 3.8,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_PISTOL50",
    ammo        = 25,
    image       = "pistol50.png",
  },

  weapon_snspistol = {
    label       = "SNS Pistol",
    description = "Small SNS pistol.",
    weight      = 2.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_SNSPISTOL",
    ammo        = 30,
    image       = "sns_pistol.png",
  },

  weapon_snspistol_mk2 = {
    label       = "SNS Pistol MK2",
    description = "SNS MK2 variant.",
    weight      = 2.8,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_SNSPISTOL_MK2",
    ammo        = 40,
    image       = "sns_pistol_mk2.png",
  },

  weapon_heavypistol = {
    label       = "Heavy Pistol",
    description = "High-damage pistol.",
    weight      = 3.8,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_HEAVYPISTOL",
    ammo        = 30,
    image       = "heavy_pistol.png",
  },

  weapon_vintagepistol = {
    label       = "Vintage Pistol",
    description = "Old-school pistol.",
    weight      = 3.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_VINTAGEPISTOL",
    ammo        = 20,
    image       = "vintage_pistol.png",
  },

  weapon_marksmanpistol = {
    label       = "Marksman Pistol",
    description = "Accurate handgun.",
    weight      = 3.2,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_MARKSMANPISTOL",
    ammo        = 24,
    image       = "marksman_pistol.png",
  },

  weapon_revolver = {
    label       = "Revolver",
    description = "Classic heavy revolver.",
    weight      = 4.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_REVOLVER",
    ammo        = 18,
    image       = "revolver.png",
  },

  weapon_revolver_mk2 = {
    label       = "Revolver MK2",
    description = "Upgraded revolver.",
    weight      = 4.3,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_REVOLVER_MK2",
    ammo        = 24,
    image       = "revolver_mk2.png",
  },

  weapon_doubleaction = {
    label       = "Double-Action",
    description = "Fast double-action revolver.",
    weight      = 3.9,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_DOUBLEACTION",
    ammo        = 18,
    image       = "doubleaction.png",
  },

  weapon_stungun = {
    label       = "Stun Gun",
    description = "Non-lethal taser.",
    weight      = 2.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_STUNGUN",
    ammo        = 8,
    image       = "stungun.png",
  },

  weapon_machinepistol = {
    label       = "Machine Pistol",
    description = "Full-auto pistol.",
    weight      = 3.2,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_MACHINEPISTOL",
    ammo        = 80,
    image       = "machine_pistol.png",
  },

  weapon_microsmg = {
    label       = "Micro SMG",
    description = "Small SMG.",
    weight      = 4.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_MICROSMG",
    ammo        = 120,
    image       = "microsmg.png",
  },

  weapon_smg = {
    label       = "SMG",
    description = "Standard SMG.",
    weight      = 4.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_SMG",
    ammo        = 120,
    image       = "smg.png",
  },

  weapon_smg_mk2 = {
    label       = "SMG MK2",
    description = "Upgraded SMG.",
    weight      = 4.8,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_SMG_MK2",
    ammo        = 150,
    image       = "smg_mk2.png",
  },

  weapon_assaultsmg = {
    label       = "Assault SMG",
    description = "High-capacity SMG.",
    weight      = 5.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_ASSAULTSMG",
    ammo        = 150,
    image       = "assault_smg.png",
  },

  weapon_combatpdw = {
    label       = "Combat PDW",
    description = "Personal defense weapon.",
    weight      = 4.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_COMBATPDW",
    ammo        = 150,
    image       = "combat_pdw.png",
  },

  weapon_minismg = {
    label       = "Mini SMG",
    description = "Compact SMG.",
    weight      = 3.8,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_MINISMG",
    ammo        = 90,
    image       = "mini_smg.png",
  },

  weapon_assaultrifle = {
    label       = "Assault Rifle",
    description = "Standard assault rifle.",
    weight      = 7.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_ASSAULTRIFLE",
    ammo        = 120,
    image       = "assaultrifle.png",
  },

  weapon_assaultrifle_mk2 = {
    label       = "Assault Rifle MK2",
    description = "Upgraded assault rifle.",
    weight      = 7.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_ASSAULTRIFLE_MK2",
    ammo        = 140,
    image       = "assaultrifle_mk2.png",
  },

  weapon_carbinerifle = {
    label       = "Carbine Rifle",
    description = "Accurate carbine rifle.",
    weight      = 7.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_CARBINERIFLE",
    ammo        = 120,
    image       = "carbinerifle.png",
  },

  weapon_carbinerifle_mk2 = {
    label       = "Carbine Rifle MK2",
    description = "Upgraded carbine rifle.",
    weight      = 7.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_CARBINERIFLE_MK2",
    ammo        = 140,
    image       = "carbinerifle_mk2.png",
  },

  weapon_advancedrifle = {
    label       = "Advanced Rifle",
    description = "High-tech assault rifle.",
    weight      = 6.8,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_ADVANCEDRIFLE",
    ammo        = 120,
    image       = "advancedrifle.png",
  },

  weapon_specialcarbine = {
    label       = "Special Carbine",
    description = "Balanced carbine.",
    weight      = 7.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_SPECIALCARBINE",
    ammo        = 120,
    image       = "specialcarbine.png",
  },

  weapon_specialcarbine_mk2 = {
    label       = "Special Carbine MK2",
    description = "Upgraded special carbine.",
    weight      = 7.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_SPECIALCARBINE_MK2",
    ammo        = 140,
    image       = "specialcarbine_mk2.png",
  },

  weapon_bullpuprifle = {
    label       = "Bullpup Rifle",
    description = "Compact rifle with good handling.",
    weight      = 6.8,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_BULLPUPRIFLE",
    ammo        = 120,
    image       = "bullpup_rifle.png",
  },

  weapon_bullpuprifle_mk2 = {
    label       = "Bullpup Rifle MK2",
    description = "Upgraded bullpup rifle.",
    weight      = 7.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_BULLPUPRIFLE_MK2",
    ammo        = 140,
    image       = "bullpup_rifle_mk2.png",
  },

  weapon_compactrifle = {
    label       = "Compact Rifle",
    description = "Light compact rifle.",
    weight      = 5.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_COMPACTRIFLE",
    ammo        = 80,
    image       = "compact_rifle.png",
  },

  weapon_gusenberg = {
    label       = "Gusenberg",
    description = "Gusenberg Sweeper (Tommy gun style).",
    weight      = 6.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_GUSENBERG",
    ammo        = 120,
    image       = "gusenberg.png",
  },

  weapon_mg = {
    label       = "MG",
    description = "General purpose machine gun.",
    weight      = 10.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_MG",
    ammo        = 200,
    image       = "mg.png",
  },

  weapon_combatmg = {
    label       = "Combat MG",
    description = "Faster-firing MG.",
    weight      = 10.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_COMBATMG",
    ammo        = 200,
    image       = "combat_mg.png",
  },

  weapon_combatmg_mk2 = {
    label       = "Combat MG MK2",
    description = "Upgraded combat MG.",
    weight      = 11.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_COMBATMG_MK2",
    ammo        = 220,
    image       = "combat_mg_mk2.png",
  },

  weapon_pumpshotgun = {
    label       = "Pump Shotgun",
    description = "Standard pump shotgun.",
    weight      = 8.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_PUMPSHOTGUN",
    ammo        = 32,
    image       = "pump_shotgun.png",
  },

  weapon_pumpshotgun_mk2 = {
    label       = "Pump Shotgun MK2",
    description = "Upgraded pump shotgun.",
    weight      = 8.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_PUMPSHOTGUN_MK2",
    ammo        = 40,
    image       = "pump_shotgun_mk2.png",
  },

  weapon_sawnoffshotgun = {
    label       = "Sawed-Off Shotgun",
    description = "Short-range shotgun.",
    weight      = 6.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_SAWNOFFSHOTGUN",
    ammo        = 12,
    image       = "sawnoff_shotgun.png",
  },

  weapon_assaultshotgun = {
    label       = "Assault Shotgun",
    description = "High-capacity shotgun.",
    weight      = 9.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_ASSAULTSHOTGUN",
    ammo        = 40,
    image       = "assault_shotgun.png",
  },

  weapon_bullpupshotgun = {
    label       = "Bullpup Shotgun",
    description = "Compact shotgun.",
    weight      = 8.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_BULLPUPSHOTGUN",
    ammo        = 36,
    image       = "bullpup_shotgun.png",
  },

  weapon_heavyshotgun = {
    label       = "Heavy Shotgun",
    description = "High-damage heavy shotgun.",
    weight      = 9.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_HEAVYSHOTGUN",
    ammo        = 20,
    image       = "heavy_shotgun.png",
  },

  weapon_sniperrifle = {
    label       = "Sniper Rifle",
    description = "Long-range precision rifle.",
    weight      = 9.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_SNIPERRIFLE",
    ammo        = 20,
    image       = "sniper_rifle.png",
  },

  weapon_heavysniper = {
    label       = "Heavy Sniper",
    description = "Very powerful sniper.",
    weight      = 10.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_HEAVYSNIPER",
    ammo        = 12,
    image       = "heavy_sniper.png",
  },

  weapon_heavysniper_mk2 = {
    label       = "Heavy Sniper MK2",
    description = "Upgraded heavy sniper.",
    weight      = 10.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_HEAVYSNIPER_MK2",
    ammo        = 12,
    image       = "heavy_sniper_mk2.png",
  },

  weapon_marksmanrifle = {
    label       = "Marksman Rifle",
    description = "Semi-auto marksman rifle.",
    weight      = 9.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_MARKSMANRIFLE",
    ammo        = 20,
    image       = "marksman_rifle.png",
  },

  weapon_marksmanrifle_mk2 = {
    label       = "Marksman Rifle MK2",
    description = "Upgraded marksman rifle.",
    weight      = 9.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_MARKSMANRIFLE_MK2",
    ammo        = 25,
    image       = "marksman_rifle_mk2.png",
  },

  weapon_rpg = {
    label       = "RPG",
    description = "Rocket-propelled grenade launcher.",
    weight      = 18.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_RPG",
    ammo        = 4,
    image       = "rpg.png",
  },

  weapon_grenadelauncher = {
    label       = "Grenade Launcher",
    description = "Explosive projectile launcher.",
    weight      = 16.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_GRENADELAUNCHER",
    ammo        = 8,
    image       = "grenade_launcher.png",
  },

  weapon_grenadelauncher_smoke = {
    label       = "Smoke GL",
    description = "Smoke grenade launcher.",
    weight      = 16.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_GRENADELAUNCHER_SMOKE",
    ammo        = 8,
    image       = "grenade_launcher_smoke.png",
  },

  weapon_hominglauncher = {
    label       = "Homing Launcher",
    description = "Lock-on rocket launcher.",
    weight      = 18.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_HOMINGLAUNCHER",
    ammo        = 4,
    image       = "homing_launcher.png",
  },

  weapon_compactlauncher = {
    label       = "Compact Launcher",
    description = "Small grenade launcher.",
    weight      = 14.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_COMPACTLAUNCHER",
    ammo        = 6,
    image       = "compact_launcher.png",
  },

  weapon_railgun = {
    label       = "Railgun",
    description = "Experimental railgun (heavy).",
    weight      = 20.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_RAILGUN",
    ammo        = 6,
    image       = "railgun.png",
  },

  weapon_grenade = {
    label       = "Grenade",
    description = "Explosive grenade.",
    weight      = 1.0,
    stack       = true,
    consume     = 1,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_GRENADE",
    ammo        = 1,
    image       = "grenade.png",
  },

  weapon_pipebomb = {
    label       = "Pipe Bomb",
    description = "Improvised explosive.",
    weight      = 1.0,
    stack       = true,
    consume     = 1,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_PIPEBOMB",
    ammo        = 1,
    image       = "pipebomb.png",
  },

  weapon_stickybomb = {
    label       = "Sticky Bomb",
    description = "Remote explosive.",
    weight      = 1.0,
    stack       = true,
    consume     = 1,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_STICKYBOMB",
    ammo        = 1,
    image       = "sticky_bomb.png",
  },

  weapon_proxmine = {
    label       = "Proximity Mine",
    description = "Explosive trip mine.",
    weight      = 1.0,
    stack       = true,
    consume     = 1,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_PROXMINE",
    ammo        = 1,
    image       = "proxmine.png",
  },

  weapon_molotov = {
    label       = "Molotov",
    description = "Incendiary bottle.",
    weight      = 1.0,
    stack       = true,
    consume     = 1,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_MOLOTOV",
    ammo        = 1,
    image       = "molotov.png",
  },

  weapon_smokegrenade = {
    label       = "Smoke Grenade",
    description = "Non-lethal smoke.",
    weight      = 1.0,
    stack       = true,
    consume     = 1,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_SMOKEGRENADE",
    ammo        = 1,
    image       = "smoke_grenade.png",
  },

  weapon_flare = {
    label       = "Flare",
    description = "Signal flare.",
    weight      = 0.5,
    stack       = true,
    consume     = 1,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_FLARE",
    ammo        = 1,
    image       = "flare.png",
  },

  weapon_petrolcan = {
    label       = "Petrol Can",
    description = "Can of petrol (flammable).",
    weight      = 6.0,
    stack       = false,
    consume     = 1,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_PETROLCAN",
    ammo        = 0,
    image       = "petrol_can.png",
  },

  weapon_knife = {
    label       = "Knife",
    description = "Sharp knife.",
    weight      = 1.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_KNIFE",
    ammo        = 0,
    image       = "knife.png",
  },

  weapon_dagger = {
    label       = "Dagger",
    description = "Small stabbing blade.",
    weight      = 1.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_DAGGER",
    ammo        = 0,
    image       = "dagger.png",
  },

  weapon_bat = {
    label       = "Baseball Bat",
    description = "Wooden baseball bat.",
    weight      = 4.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_BAT",
    ammo        = 0,
    image       = "bat.png",
  },

  weapon_crowbar = {
    label       = "Crowbar",
    description = "Prying crowbar.",
    weight      = 3.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_CROWBAR",
    ammo        = 0,
    image       = "crowbar.png",
  },

  weapon_hammer = {
    label       = "Hammer",
    description = "Heavy hammer.",
    weight      = 3.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_HAMMER",
    ammo        = 0,
    image       = "hammer.png",
  },

  weapon_golfclub = {
    label       = "Golf Club",
    description = "Old golf club.",
    weight      = 3.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_GOLFCLUB",
    ammo        = 0,
    image       = "golf_club.png",
  },

  weapon_poolcue = {
    label       = "Pool Cue",
    description = "Cue stick.",
    weight      = 2.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_POOLCUE",
    ammo        = 0,
    image       = "pool_cue.png",
  },

  weapon_machete = {
    label       = "Machete",
    description = "Large bladed machete.",
    weight      = 2.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_MACHETE",
    ammo        = 0,
    image       = "machete.png",
  },

  weapon_switchblade = {
    label       = "Switchblade",
    description = "Folding knife.",
    weight      = 1.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_SWITCHBLADE",
    ammo        = 0,
    image       = "switchblade.png",
  },

  weapon_knuckle = {
    label       = "Knuckledusters",
    description = "Brass knuckles.",
    weight      = 0.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_KNUCKLE",
    ammo        = 0,
    image       = "knuckleduster.png",
  },

  weapon_nightstick = {
    label       = "Nightstick",
    description = "Police baton.",
    weight      = 2.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_NIGHTSTICK",
    ammo        = 0,
    image       = "nightstick.png",
  },

  weapon_bottle = {
    label       = "Broken Bottle",
    description = "Glass bottle (broken).",
    weight      = 1.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_BOTTLE",
    ammo        = 0,
    image       = "bottle.png",
  },

  weapon_hatchet = {
    label       = "Hatchet",
    description = "Small axe.",
    weight      = 2.5,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_HATCHET",
    ammo        = 0,
    image       = "hatchet.png",
  },

  weapon_wrench = {
    label       = "Wrench",
    description = "Heavy wrench.",
    weight      = 3.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_WRENCH",
    ammo        = 0,
    image       = "wrench.png",
  },

  weapon_fireextinguisher = {
    label       = "Fire Extinguisher",
    description = "For putting out fires.",
    weight      = 8.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_FIREEXTINGUISHER",
    ammo        = 0,
    image       = "fire_extinguisher.png",
  },

  weapon_ball = {
    label       = "Baseball",
    description = "Just a ball.",
    weight      = 0.5,
    stack       = true,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_BALL",
    ammo        = 0,
    image       = "ball.png",
  },

  weapon_snowball = {
    label       = "Snowball",
    description = "Seasonal throwable.",
    weight      = 0.5,
    stack       = true,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_SNOWBALL",
    ammo        = 0,
    image       = "snowball.png",
  },

  weapon_bzgas = {
    label       = "BZ Gas",
    description = "Toxic gas canister.",
    weight      = 2.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_BZGAS",
    ammo        = 0,
    image       = "bz_gas.png",
  },

  weapon_firework = {
    label       = "Firework Launcher",
    description = "Festive launcher.",
    weight      = 6.0,
    stack       = false,
    consume     = 0,
    close       = true,
    category    = "weapon",
    weaponName  = "WEAPON_FIREWORK",
    ammo        = 6,
    image       = "firework_launcher.png",
  },


}



function GetItemDefinition(name)
  return Items[name]
end
